2015-10-17 20:57:40 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [1045] Access denied for user \'\'@\'localhost\' (using password: NO)',
  'enabled' => true,
)
Request URL: /
Stack Trace:
#0 /home/vagrant/Repo/gigsmanager/lib/Cake/Model/Datasource/DboSource.php(262): Mysql->connect()
#1 /home/vagrant/Repo/gigsmanager/lib/Cake/Model/ConnectionManager.php(107): DboSource->__construct(Array)
#2 /home/vagrant/Repo/gigsmanager/lib/Cake/Model/Model.php(3290): ConnectionManager::getDataSource('default')
#3 /home/vagrant/Repo/gigsmanager/lib/Cake/Model/Model.php(1107): Model->setDataSource('default')
#4 /home/vagrant/Repo/gigsmanager/lib/Cake/Model/Model.php(3312): Model->setSource('gigs')
#5 /home/vagrant/Repo/gigsmanager/lib/Cake/Model/Model.php(1318): Model->getDataSource()
#6 /home/vagrant/Repo/gigsmanager/lib/Cake/Model/Model.php(1401): Model->schema()
#7 /home/vagrant/Repo/gigsmanager/lib/Cake/Controller/Component/PaginatorComponent.php(398): Model->hasField('date')
#8 /home/vagrant/Repo/gigsmanager/lib/Cake/Controller/Component/PaginatorComponent.php(144): PaginatorComponent->validateSort(Object(Gig), Array, Array)
#9 /home/vagrant/Repo/gigsmanager/app/Controller/GigsController.php(33): PaginatorComponent->paginate('Gig')
#10 [internal function]: GigsController->index('home')
#11 /home/vagrant/Repo/gigsmanager/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(GigsController), Array)
#12 /home/vagrant/Repo/gigsmanager/lib/Cake/Routing/Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#13 /home/vagrant/Repo/gigsmanager/lib/Cake/Routing/Dispatcher.php(162): Dispatcher->_invoke(Object(GigsController), Object(CakeRequest), Object(CakeResponse))
#14 /home/vagrant/Repo/gigsmanager/app/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#15 {main}
2015-10-17 20:57:42 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [1045] Access denied for user \'\'@\'localhost\' (using password: NO)',
  'enabled' => true,
)
Request URL: /gigs
Stack Trace:
#0 /home/vagrant/Repo/gigsmanager/lib/Cake/Model/Datasource/DboSource.php(262): Mysql->connect()
#1 /home/vagrant/Repo/gigsmanager/lib/Cake/Model/ConnectionManager.php(107): DboSource->__construct(Array)
#2 /home/vagrant/Repo/gigsmanager/lib/Cake/Model/Model.php(3290): ConnectionManager::getDataSource('default')
#3 /home/vagrant/Repo/gigsmanager/lib/Cake/Model/Model.php(1107): Model->setDataSource('default')
#4 /home/vagrant/Repo/gigsmanager/lib/Cake/Model/Model.php(3312): Model->setSource('gigs')
#5 /home/vagrant/Repo/gigsmanager/lib/Cake/Model/Model.php(1318): Model->getDataSource()
#6 /home/vagrant/Repo/gigsmanager/lib/Cake/Model/Model.php(1401): Model->schema()
#7 /home/vagrant/Repo/gigsmanager/lib/Cake/Controller/Component/PaginatorComponent.php(398): Model->hasField('date')
#8 /home/vagrant/Repo/gigsmanager/lib/Cake/Controller/Component/PaginatorComponent.php(144): PaginatorComponent->validateSort(Object(Gig), Array, Array)
#9 /home/vagrant/Repo/gigsmanager/app/Controller/GigsController.php(33): PaginatorComponent->paginate('Gig')
#10 [internal function]: GigsController->index()
#11 /home/vagrant/Repo/gigsmanager/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(GigsController), Array)
#12 /home/vagrant/Repo/gigsmanager/lib/Cake/Routing/Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#13 /home/vagrant/Repo/gigsmanager/lib/Cake/Routing/Dispatcher.php(162): Dispatcher->_invoke(Object(GigsController), Object(CakeRequest), Object(CakeResponse))
#14 /home/vagrant/Repo/gigsmanager/app/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#15 {main}
2020-10-22 21:28:54 Error: Fatal Error (64): Cannot use 'Object' as class name as it is reserved in [/Users/abottiroli/Sites/gigsmanager-cake/lib/Cake/Core/Object.php, line 31]
2020-10-22 21:28:54 Error: [InternalErrorException] Internal Server Error
Request URL: /
Stack Trace:
#0 /Users/abottiroli/Sites/gigsmanager-cake/lib/Cake/Error/ErrorHandler.php(205): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', '/Users/abottiro...', 31)
#1 /Users/abottiroli/Sites/gigsmanager-cake/lib/Cake/Core/App.php(931): ErrorHandler::handleError(64, 'Cannot use 'Obj...', '/Users/abottiro...', 31, Array)
#2 /Users/abottiroli/Sites/gigsmanager-cake/lib/Cake/Core/App.php(904): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
